In WCS.all_world2pix doctest, locate data file with module.__path__
When the doctest is run under `python setup.py test`, it fails with:

    IOError: File does not exist: u'tests/data/j94f05bgq_flt.fits'

Also, as example code that a user might run, the path
`tests/data/j94f05bgq_flt.fits` will not make sense.

This patch copies the approach of the doctests for
`astropy.io.ascii.daophot` and `astropy.io.ascii.ipac` of locating
the data file with `module.__path__`, which will work even outside of
the module code.