Update angle_utilities.py
degrees, unlike radians, appear to call sexagesimal_to_string which has int(values[1]), but nan cannot be converted to an integer, so it fails.
~/local/astropy/astropy/coordinates/angle_utilities.py in sexagesimal_to_string(values, precision, pad, sep, fields)
--> 639                           int(values[1]), values[2],
ValueError: cannot convert float NaN to integer
Resolve this type error by using np.nan_to_num() method
-->639                        int(np.nan_to_num(values[1])), values[2],

After that, the ide would not give any type of error in a code.