Fix broken WCS transformation from ITRS to ICRS
Astropy 3.2 broke the use of the reproject package to
transform from a HEALPix image in ICRS coordinates to
a WCS in ITRS coordinates. I can reproduce this with
astropy 3.2.3 and master.

The reason is that the default representation for ITRS
frames is cartesian, but WCS transformations require
spherical representation.

Here is the example that was failing:

```pycon
>>> from astropy.io.fits import Header
>>> import numpy as np
>>> from reproject.healpix import reproject_from_healpix
>>> header = Header({'NAXIS': 2,
...                  'NAXIS1': 335,
...                  'NAXIS2': 168,
...                  'CRPIX1': 168.0,
...                  'CRPIX2': 84.5,
...                  'CRVAL1': 0,
...                  'CRVAL2': 0.0,
...                  'CDELT1': -0.9675041009449499,
...                  'CDELT2': 0.9646246244540423,
...                  'CTYPE1': 'TLON-AIT',
...                  'CTYPE2': 'TLAT-AIT',
...                  'RADESYS': 'ITRS ',
...                  'DATE-OBS': '2017-08-17T12:41:04.444'})
>>> hpx = np.zeros(12288)
>>> reproject_from_healpix((hpx, 'ICRS'), header, nested=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/reproject/healpix/high_level.py", line 74, in reproject_from_healpix
    order=order, nested=nested)
  File "/usr/lib/python3.7/site-packages/reproject/healpix/core.py", line 59, in healpix_to_image
    world_in = wcs_out.pixel_to_world(xinds, yinds).transform_to(coord_system_in)
  File "/usr/lib/python3.7/site-packages/astropy/wcs/wcsapi/high_level_api.py", line 227, in pixel_to_world
    result.append(klass(*args[key], *ar, **kwargs[key], **kw))
  File "/usr/lib/python3.7/site-packages/astropy/coordinates/sky_coordinate.py", line 272, in __init__
    self._sky_coord_frame = frame_cls(copy=copy, **frame_kwargs)
  File "/usr/lib/python3.7/site-packages/astropy/coordinates/baseframe.py", line 507, in __init__
    **repr_kwargs)
  File "/usr/lib/python3.7/site-packages/astropy/coordinates/representation.py", line 1028, in __init__
    .format(self.__class__.__name__))
ValueError: x, y, and z are required to instantiate CartesianRepresentation
```