fix "_POSIX_C_SOURCE redefined" error and warnings
Compile logs are full of
```
  .../3.14.2/include/python3.14/pyconfig.h:2007:9: warning: ‘_POSIX_C_SOURCE’ redefined
   2007 | #define _POSIX_C_SOURCE 200809L
        |         ^~~~~~~~~~~~~~~
```

warnings, and this causes a compilation error for
`signature_deprecations.c` since it uses `-Werror`:
```
  creating /tmp/.../tmppg5jsirv.build-temp/astropy/cosmology/_src
  ccache /usr/bin/cc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -march=native -mtune=native -O3 -fPIC -I/home/.../.pyenv/versions/3.14.2/include/python3.14 -c astropy/cosmology/_src/signature_deprecations.c -o /tmp/.../tmppg5jsirv.build-temp/astropy/cosmology/_src/signature_deprecations.o -Werror -Wall
  In file included from /home/.../.pyenv/versions/3.14.2/include/python3.14/Python.h:14,
                   from astropy/cosmology/_src/signature_deprecations.c:7:
  /home/.../.pyenv/versions/3.14.2/include/python3.14/pyconfig.h:2007:9: error: ‘_POSIX_C_SOURCE’ redefined [-Werror]
   2007 | #define _POSIX_C_SOURCE 200809L
        |         ^~~~~~~~~~~~~~~
  In file included from /usr/include/bits/libc-header-start.h:33,
                   from /usr/include/stdio.h:28,
                   from astropy/cosmology/_src/signature_deprecations.c:6:
  /usr/include/features.h:319:10: note: this is the location of the previous definition
    319 | # define _POSIX_C_SOURCE        202405L
        |          ^~~~~~~~~~~~~~~
  cc1: all warnings being treated as errors
```

To fix this, `Python.h` should always be included first:
https://github.com/python/cpython/issues/61322
https://docs.python.org/3/c-api/intro.html#include-files